import 'package:flutter/material.dart';
import '../../core/services/lecturador_service.dart';

class BuscarSuministroPage extends StatefulWidget { const BuscarSuministroPage({super.key}); @override State<BuscarSuministroPage> createState()=>_BuscarSuministroPageState(); }
class _BuscarSuministroPageState extends State<BuscarSuministroPage>{
  static const Color primary=Color(0xFF0F3D57), secondary=Color(0xFF1DA1C2), background=Color(0xFFEFF7FB), muted=Color(0xFF7B8794);
  final LecturadorService service=LecturadorService(); final TextEditingController codigoController=TextEditingController(); bool cargando=false; String error='';
  @override void dispose(){codigoController.dispose();super.dispose();}
  String _txt(dynamic v,[String f='-']){ if(v==null)return f; final s=v.toString().trim(); return s.isEmpty||s=='null'?f:s; }
  Future<void> buscar()async{ final codigo=codigoController.text.trim(); if(codigo.isEmpty){setState(()=>error='Ingresa o escanea el código del suministro.');return;} setState(()=>{cargando=true,error=''}); try{ final s=await service.buscarSuministro(codigo); if(!mounted)return; setState(()=>cargando=false); Navigator.pushNamed(context,'/detalle-suministro',arguments:s); }catch(e){ if(!mounted)return; setState(()=>{error=e.toString().replaceFirst('Exception: ',''),cargando=false}); }}
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:background,bottomNavigationBar:_LectorBottomNav(currentIndex:1,onTap:_go),body:SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:46,height:46,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16)),child:IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_back_rounded,color:primary))),const SizedBox(width:12),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Escaneo de suministro',style:TextStyle(color:muted,fontWeight:FontWeight.w700)),Text('Buscar suministro',style:TextStyle(color:primary,fontSize:24,fontWeight:FontWeight.w900))]))]),const SizedBox(height:22),Container(width:double.infinity,padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:const Color(0xFF09283A),borderRadius:BorderRadius.circular(28)),child:Column(children:[const Icon(Icons.qr_code_scanner_rounded,color:Colors.white,size:86),const SizedBox(height:16),const Text('Apunta la cámara al QR o ingresa el código manualmente',textAlign:TextAlign.center,style:TextStyle(color:Colors.white,fontWeight:FontWeight.w800)),const SizedBox(height:20),TextField(controller:codigoController,textInputAction:TextInputAction.search,onSubmitted:(_)=>buscar(),style:const TextStyle(color:Colors.white),decoration:InputDecoration(hintText:'Ej. SUM-F70DEB8',hintStyle:TextStyle(color:Colors.white.withOpacity(.6)),filled:true,fillColor:Colors.white.withOpacity(.12),prefixIcon:const Icon(Icons.search,color:Colors.white),border:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide.none))),const SizedBox(height:14),SizedBox(width:double.infinity,height:52,child:ElevatedButton.icon(onPressed:cargando?null:buscar,icon:cargando?const SizedBox(width:20,height:20,child:CircularProgressIndicator(strokeWidth:2,color:Colors.white)):const Icon(Icons.qr_code_rounded),label:Text(cargando?'Buscando...':'Buscar código'),style:ElevatedButton.styleFrom(backgroundColor:secondary,foregroundColor:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16)))))])),if(error.isNotEmpty)Padding(padding:const EdgeInsets.only(top:16),child:Container(width:double.infinity,padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:const Color(0xFFFFECEC),borderRadius:BorderRadius.circular(16)),child:Text(error,style:const TextStyle(color:Color(0xFFD93025),fontWeight:FontWeight.w800))))]))));
  void _go(int i){ if(i==0)Navigator.pushReplacementNamed(context,'/lector-home'); if(i==2)Navigator.pushReplacementNamed(context,'/registrar-lectura'); if(i==3)Navigator.pushReplacementNamed(context,'/historial-lecturas'); }
}
class _LectorBottomNav extends StatelessWidget{final int currentIndex;final Function(int) onTap;const _LectorBottomNav({required this.currentIndex,required this.onTap});@override Widget build(BuildContext context)=>NavigationBar(selectedIndex:currentIndex,onDestinationSelected:onTap,height:76,destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),label:'Inicio'),NavigationDestination(icon:Icon(Icons.qr_code_rounded),label:'QR'),NavigationDestination(icon:Icon(Icons.water_drop_rounded),label:'Lectura'),NavigationDestination(icon:Icon(Icons.history_rounded),label:'Historial')]);}
