spring.application.name=jass-huacariz-api

# PUERTO DEL BACKEND
server.port=8080

# BASE DE DATOS POSTGRESQL REMOTA
spring.datasource.url=jdbc:postgresql://100.76.98.110:5432/jass_huacariz_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration