ALTER TABLE lecturas
ADD COLUMN IF NOT EXISTS cambio_medidor BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lectura_inicial_nuevo_medidor NUMERIC(10,3),
ADD COLUMN IF NOT EXISTS observacion_cambio_medidor VARCHAR(255),
ADD COLUMN IF NOT EXISTS consumo_inusual BOOLEAN NOT NULL DEFAULT FALSE;