import 'package:flutter/material.dart';
import '../../core/services/cliente_service.dart';
import '../../core/services/recibo_service.dart';
import '../../core/services/pago_service.dart';
import '../../core/services/tarifa_service.dart';

class AdminReportesPage extends StatefulWidget{const AdminReportesPage({super.key});@override State<AdminReportesPage> createState()=>_AdminReportesPageState();}
class _AdminReportesPageState extends State<AdminReportesPage>{
  static const Color primary=Color(0xFF0F3D57), secondary=Color(0xFF1DA1C2), background=Color(0xFFEFF7FB), muted=Color(0xFF7B8794);
  final ClienteService clienteService=ClienteService(); final ReciboService reciboService=ReciboService(); final PagoService pagoService=PagoService(); final TarifaService tarifaService=TarifaService();
  List<Map<String,dynamic>> clientes=[],recibos=[],pagos=[],tarifas=[]; bool cargando=false; String error='';
  @override void initState(){super.initState(); cargar();}
  double _num(dynamic v)=>v is num?v.toDouble():double.tryParse('$v')??0; String _estado(Map<String,dynamic> r)=>(r['estadoRecibo']??r['estado']??'').toString().toUpperCase();
  Future<void> cargar()async{setState(()=>{cargando=true,error=''});try{final d=await Future.wait([clienteService.listarClientes(),reciboService.listarRecibosAdmin(),pagoService.listarPagos(),tarifaService.listarTarifas()]);if(!mounted)return;setState(()=>{clientes=d[0],recibos=d[1],pagos=d[2],tarifas=d[3],cargando=false});}catch(e){if(!mounted)return;setState(()=>{error=e.toString().replaceFirst('Exception: ',''),cargando=false});}}
  int get totalSuministros=>clientes.fold(0,(s,c)=>s+((c['suministros'] is List)?(c['suministros'] as List).length:0));
  double get totalEmitido=>recibos.fold(0,(s,r)=>s+_num(r['total'])); double get recaudado=>pagos.fold(0,(s,p)=>s+_num(p['monto'])); double get carteraVencida=>recibos.where((r)=>_estado(r)=='VENCIDO').fold(0,(s,r)=>s+_num(r['total'])); double get saldoPendiente=>totalEmitido-recaudado; double get consumoTotal=>recibos.fold(0,(s,r)=>s+_num(r['consumoM3'])); double get mantenimiento=>recibos.fold(0,(s,r)=>s+_num(r['cargoMantenimiento'])); double get lector=>recibos.fold(0,(s,r)=>s+_num(r['cargoLector']));
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:background,bottomNavigationBar:_AdminBottomNav(currentIndex:4,onTap:_go),body:SafeArea(child:RefreshIndicator(onRefresh:cargar,child:SingleChildScrollView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Indicadores',style:TextStyle(color:muted,fontWeight:FontWeight.w700)),SizedBox(height:4),Text('Reportes',style:TextStyle(color:primary,fontSize:24,fontWeight:FontWeight.w900))])),IconButton(onPressed:cargar,icon:const Icon(Icons.refresh,color:primary))]),const SizedBox(height:16),if(cargando)const Center(child:Padding(padding:EdgeInsets.all(24),child:CircularProgressIndicator())),if(error.isNotEmpty)_Error(error:error,onRetry:cargar),if(!cargando&&error.isEmpty)GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.1,children:[_Card('Clientes','${clientes.length}',Icons.groups_rounded),_Card('Suministros','$totalSuministros',Icons.water_drop_rounded),_Card('Recibos emitidos','${recibos.length}',Icons.receipt_long_rounded),_Card('Recaudación','S/ ${recaudado.toStringAsFixed(2)}',Icons.payments_rounded),_Card('Saldo pendiente','S/ ${saldoPendiente.toStringAsFixed(2)}',Icons.pending_actions_rounded),_Card('Cartera vencida','S/ ${carteraVencida.toStringAsFixed(2)}',Icons.warning_rounded),_Card('Consumo total','${consumoTotal.toStringAsFixed(0)} m³',Icons.bar_chart_rounded),_Card('Mantenimiento','S/ ${mantenimiento.toStringAsFixed(2)}',Icons.build_rounded),_Card('Pago lector','S/ ${lector.toStringAsFixed(2)}',Icons.person_search_rounded),_Card('Tarifas','${tarifas.length}',Icons.attach_money_rounded)])])))));
  void _go(int i){if(i==0)Navigator.pushReplacementNamed(context,'/admin-dashboard');if(i==1)Navigator.pushReplacementNamed(context,'/admin-clientes');if(i==2)Navigator.pushReplacementNamed(context,'/admin-tarifas');if(i==3)Navigator.pushReplacementNamed(context,'/admin-recibos');}
}
class _Card extends StatelessWidget{final String title,value;final IconData icon;const _Card(this.title,this.value,this.icon);@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22),border:Border.all(color:Color(0xFFE2EDF3))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,color:Color(0xFF1DA1C2)),const Spacer(),Text(value,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Color(0xFF0F3D57),fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:4),Text(title,style:const TextStyle(color:Color(0xFF7B8794),fontWeight:FontWeight.w800,fontSize:12))]));}
class _Error extends StatelessWidget{final String error;final VoidCallback onRetry;const _Error({required this.error,required this.onRetry});@override Widget build(BuildContext context)=>Container(width:double.infinity,padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:Color(0xFFFFECEC),borderRadius:BorderRadius.circular(18)),child:Column(children:[Text(error,textAlign:TextAlign.center,style:const TextStyle(color:Color(0xFFD93025),fontWeight:FontWeight.w800)),TextButton(onPressed:onRetry,child:const Text('Reintentar'))]));}
class _AdminBottomNav extends StatelessWidget{final int currentIndex;final Function(int) onTap;const _AdminBottomNav({required this.currentIndex,required this.onTap});@override Widget build(BuildContext context)=>NavigationBar(selectedIndex:currentIndex,onDestinationSelected:onTap,height:76,destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),label:'Inicio'),NavigationDestination(icon:Icon(Icons.groups_outlined),label:'Clientes'),NavigationDestination(icon:Icon(Icons.attach_money_rounded),label:'Tarifas'),NavigationDestination(icon:Icon(Icons.receipt_long_outlined),label:'Recibos'),NavigationDestination(icon:Icon(Icons.bar_chart_rounded),label:'Reportes')]);}
