import 'package:flutter/material.dart';

import '../../core/services/recibo_service.dart';

class AdminRecibosPage extends StatefulWidget {
  const AdminRecibosPage({super.key});
  @override State<AdminRecibosPage> createState() => _AdminRecibosPageState();
}

class _AdminRecibosPageState extends State<AdminRecibosPage> {
  static const Color primary = Color(0xFF0F3D57), secondary = Color(0xFF1DA1C2), background = Color(0xFFEFF7FB), muted = Color(0xFF7B8794);
  final ReciboService reciboService = ReciboService();
  List<Map<String,dynamic>> recibos = [];
  bool cargando = false;
  String error = '';
  String filtro = 'TODOS';

  @override void initState(){ super.initState(); cargar(); }
  String _txt(dynamic v,[String f='-']){ if(v==null) return f; final s=v.toString().trim(); return s.isEmpty||s=='null'?f:s; }
  double _num(dynamic v)=> v is num ? v.toDouble() : double.tryParse('$v') ?? 0;
  int _id(Map<String,dynamic> r)=> r['id'] is int ? r['id'] : int.tryParse('${r['id']??r['idRecibo']??0}') ?? 0;
  String _estado(Map<String,dynamic> r)=> _txt(r['estadoRecibo']??r['estado'],'PENDIENTE').toUpperCase();
  String _periodo(Map<String,dynamic> r){ const m=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre']; final mes=int.tryParse('${r['mes']??1}')??1; return '${m[(mes-1).clamp(0,11)]} ${r['anio']??''}'.trim(); }
  List<Map<String,dynamic>> get filtrados => filtro=='TODOS' ? recibos : recibos.where((r)=>_estado(r)==filtro).toList();
  int get pendientes => recibos.where((r)=>_estado(r)=='PENDIENTE').length;
  int get pagados => recibos.where((r)=>_estado(r)=='PAGADO').length;
  int get vencidos => recibos.where((r)=>_estado(r)=='VENCIDO').length;
  double get totalPendiente => recibos.where((r)=>_estado(r)!='PAGADO').fold(0.0,(s,r)=>s+_num(r['total']));

  Future<void> cargar() async { setState(()=>{cargando=true,error=''}); try{ final data=await reciboService.listarRecibosAdmin(); if(!mounted)return; setState(()=>{recibos=data,cargando=false}); }catch(e){ if(!mounted)return; setState(()=>{error=e.toString().replaceFirst('Exception: ',''),cargando=false}); }}
  Future<void> pagar(Map<String,dynamic> r) async { final id=_id(r); final ctrl=TextEditingController(text:'PRESENCIAL-${DateTime.now().millisecondsSinceEpoch}'); final ok=await showDialog<bool>(context: context, builder: (_)=>AlertDialog(title: const Text('Registrar pago presencial'), content: TextField(controller: ctrl, decoration: const InputDecoration(labelText: 'Código de operación')), actions: [TextButton(onPressed:()=>Navigator.pop(context,false), child: const Text('Cancelar')), ElevatedButton(onPressed:()=>Navigator.pop(context,true), child: const Text('Confirmar'))])); if(ok!=true)return; try{ await reciboService.pagarReciboAdmin(idRecibo:id, metodoPago:'PRESENCIAL', codigoOperacion:ctrl.text.trim()); if(!mounted)return; ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Pago registrado correctamente'), backgroundColor: Color(0xFF1F8F4D))); cargar(); }catch(e){ if(!mounted)return; ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.toString().replaceFirst('Exception: ','')), backgroundColor: const Color(0xFFD93025))); }}

  @override Widget build(BuildContext context){ return Scaffold(backgroundColor: background, bottomNavigationBar: _AdminBottomNav(currentIndex:3,onTap:_go), body: SafeArea(child: RefreshIndicator(onRefresh:cargar, child: SingleChildScrollView(physics: const AlwaysScrollableScrollPhysics(), padding: const EdgeInsets.all(22), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children:[
    Row(children:[const Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children:[Text('Facturación mensual', style: TextStyle(color: muted,fontWeight: FontWeight.w700)), SizedBox(height:4), Text('Recibos', style: TextStyle(color: primary,fontSize:24,fontWeight: FontWeight.w900))])), IconButton(onPressed:cargar, icon: const Icon(Icons.refresh_rounded,color:primary))]),
    const SizedBox(height:18), Container(width: double.infinity, padding: const EdgeInsets.all(18), decoration: BoxDecoration(color: Colors.white,borderRadius: BorderRadius.circular(22)), child: Row(children:[Expanded(child:_Mini('Pendientes','$pendientes')), Expanded(child:_Mini('Pagados','$pagados')), Expanded(child:_Mini('Vencidos','$vencidos')), Expanded(child:_Mini('Saldo','S/ ${totalPendiente.toStringAsFixed(2)}'))])),
    const SizedBox(height:14), SingleChildScrollView(scrollDirection: Axis.horizontal, child: Row(children: ['TODOS','PENDIENTE','PAGADO','VENCIDO'].map((f)=>Padding(padding: const EdgeInsets.only(right:8), child: ChoiceChip(label: Text(f), selected: filtro==f, selectedColor: secondary, onSelected: (_)=>setState(()=>filtro=f)))).toList())),
    const SizedBox(height:16), if(cargando) const Center(child: Padding(padding: EdgeInsets.all(24), child: CircularProgressIndicator())), if(error.isNotEmpty) _Error(error:error,onRetry:cargar), if(!cargando && error.isEmpty) ...filtrados.map((r)=>_ReciboCard(codigo:_txt(r['codigoRecibo']), suministro:_txt(r['codigoSuministro']), direccion:_txt(r['direccionSuministro']), periodo:_periodo(r), consumo:_num(r['consumoM3']), total:_num(r['total']), estado:_estado(r), onPagar:_estado(r)=='PAGADO'?null:()=>pagar(r))).toList(),
  ]))))); }
  void _go(int i){ if(i==0)Navigator.pushReplacementNamed(context,'/admin-dashboard'); if(i==1)Navigator.pushReplacementNamed(context,'/admin-clientes'); if(i==2)Navigator.pushReplacementNamed(context,'/admin-tarifas'); if(i==4)Navigator.pushReplacementNamed(context,'/admin-reportes'); }
}
class _Mini extends StatelessWidget{ final String l,v; const _Mini(this.l,this.v); @override Widget build(BuildContext context)=>Column(crossAxisAlignment: CrossAxisAlignment.start, children:[Text(l, style: const TextStyle(color: Color(0xFF7B8794),fontSize:11,fontWeight:FontWeight.w800)), const SizedBox(height:5), Text(v, style: const TextStyle(color: Color(0xFF0F3D57),fontWeight:FontWeight.w900))]);}
class _ReciboCard extends StatelessWidget{ final String codigo,suministro,direccion,periodo,estado; final double consumo,total; final VoidCallback? onPagar; const _ReciboCard({required this.codigo,required this.suministro,required this.direccion,required this.periodo,required this.consumo,required this.total,required this.estado,this.onPagar}); @override Widget build(BuildContext context)=>Container(margin: const EdgeInsets.only(bottom:14), padding: const EdgeInsets.all(16), decoration: BoxDecoration(color: Colors.white,borderRadius: BorderRadius.circular(22),border: Border.all(color: Color(0xFFE2EDF3))), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children:[Row(children:[Expanded(child: Text(codigo, style: const TextStyle(color: Color(0xFF0F3D57),fontWeight:FontWeight.w900,fontSize:17))), _Badge(estado)]), const SizedBox(height:8), Text('$suministro · $periodo', style: const TextStyle(color: Color(0xFF7B8794),fontWeight:FontWeight.w700)), Text(direccion, style: const TextStyle(color: Color(0xFF7B8794))), const SizedBox(height:10), Row(children:[Expanded(child: Text('Consumo: ${consumo.toStringAsFixed(2)} m³', style: const TextStyle(fontWeight:FontWeight.w800))), Text('S/ ${total.toStringAsFixed(2)}', style: const TextStyle(color: Color(0xFF0F3D57),fontWeight:FontWeight.w900,fontSize:18))]), if(onPagar!=null) Padding(padding: const EdgeInsets.only(top:10), child: SizedBox(width: double.infinity, child: ElevatedButton(onPressed:onPagar, child: const Text('Marcar como pagado'))))]));}
class _Badge extends StatelessWidget{ final String e; const _Badge(this.e); @override Widget build(BuildContext context){ final p=e=='PAGADO'; final v=e=='VENCIDO'; return Container(padding: const EdgeInsets.symmetric(horizontal:10,vertical:6), decoration: BoxDecoration(color:p?Color(0xFFEAF8EF):v?Color(0xFFFFECEC):Color(0xFFFFF3DF), borderRadius: BorderRadius.circular(50)), child: Text(e, style: TextStyle(fontSize:11,fontWeight:FontWeight.w900,color:p?Color(0xFF1F8F4D):v?Color(0xFFD93025):Color(0xFFC77700)))); }}
class _Error extends StatelessWidget{ final String error; final VoidCallback onRetry; const _Error({required this.error, required this.onRetry}); @override Widget build(BuildContext context)=>Container(width: double.infinity,padding: const EdgeInsets.all(18), decoration: BoxDecoration(color: Color(0xFFFFECEC), borderRadius: BorderRadius.circular(18)), child: Column(children:[Text(error, textAlign: TextAlign.center, style: const TextStyle(color: Color(0xFFD93025),fontWeight:FontWeight.w800)), TextButton(onPressed:onRetry, child: const Text('Reintentar'))]));}
class _AdminBottomNav extends StatelessWidget{ final int currentIndex; final Function(int) onTap; const _AdminBottomNav({required this.currentIndex, required this.onTap}); @override Widget build(BuildContext context)=>NavigationBar(selectedIndex:currentIndex,onDestinationSelected:onTap,height:76,destinations: const [NavigationDestination(icon:Icon(Icons.home_outlined),label:'Inicio'),NavigationDestination(icon:Icon(Icons.groups_outlined),label:'Clientes'),NavigationDestination(icon:Icon(Icons.attach_money_rounded),label:'Tarifas'),NavigationDestination(icon:Icon(Icons.receipt_long_rounded),label:'Recibos'),NavigationDestination(icon:Icon(Icons.bar_chart_rounded),label:'Reportes')]);}
